# Generated by Django 5.0.2 on 2024-02-29 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('person_id', models.AutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('second_name', models.CharField(blank=True, db_column='second_name', max_length=100, null=True)),
                ('first_last_name', models.CharField(db_column='first_last_name', max_length=100)),
                ('second_last_name', models.CharField(blank=True, db_column='second_last_name', max_length=100, null=True)),
                ('date_of_birth', models.DateField(db_column='date_of_birth')),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=1, null=True)),
                ('address', models.CharField(db_column='address', max_length=100)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('country', models.CharField(db_column='country', max_length=100)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'People',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_cod', models.CharField(db_column='permission_cod', max_length=3, primary_key=True, serialize=False)),
                ('permission_name', models.CharField(db_column='permission_name', max_length=100)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=100)),
                ('role_description', models.CharField(db_column='role_description', max_length=255)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('role_permission_id', models.AutoField(db_column='role_permission_id', primary_key=True, serialize=False)),
                ('permission_id', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='login.permissions')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='login.roles')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'RolePermissions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('is_locked', models.BooleanField(db_column='is_locked', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='login.people')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_role_id', models.AutoField(db_column='user_role_id', primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='login.roles')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'UserRoles',
            },
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('audit_log_id', models.AutoField(db_column='audit_log_id', primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_column='action_type', max_length=255)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_column='action_date')),
                ('additional_details', models.CharField(db_column='additional_details', max_length=255)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'AuditLogs',
            },
        ),
    ]
